# Generated by Django 6.0.2 on 2026-04-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('instrument_type', models.CharField(default='currency_pair', max_length=20)),
                ('bid_price', models.FloatField(blank=True, null=True)),
                ('ask_price', models.FloatField(blank=True, null=True)),
                ('flat_rate', models.FloatField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('source', models.CharField(max_length=100)),
                ('is_flat_rate', models.BooleanField(default=True)),
            ],
        ),
    ]
