# Generated by Django 6.0.2 on 2026-04-11 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forexchange', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_name', models.CharField(max_length=20)),
                ('currency_symbol', models.CharField(max_length=10)),
                ('currency_type', models.CharField(choices=[('commodity_money', 'Commodity Money'), ('fiat_money', 'Fiat Money'), ('fiduciary_money', 'Fiduciary Money'), ('crypto', 'Cryptocurrency')], max_length=100)),
            ],
        ),
    ]
