# Generated by Django 6.0.2 on 2026-04-11 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forexchange', '0002_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name_plural': 'currencies'},
        ),
    ]
