# Generated by Django 6.0.2 on 2026-03-16 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_auto_20260316_1800'),
    ]

    operations = [
    ]
