# Generated by Django 6.0.2 on 2026-03-16 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0004_entitytype_remove_entity_name_entity_entity_type'),
        ('person', '0004_auto_20260316_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='entity_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.entitytype'),
        ),
    ]
