# Generated by Django 6.0.2 on 2026-03-14 15:35

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
        ('tracker', '0009_alter_unit_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='goal_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.item'),
        ),
        migrations.AddField(
            model_name='goal',
            name='goal_item_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='tracker.unit'),
        ),
        migrations.AddField(
            model_name='goal',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='goals.goal'),
        ),
        migrations.AddField(
            model_name='goal',
            name='start_date',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AddField(
            model_name='goal',
            name='target_count_per_sample',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='target_sample_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='target_sampling_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='daily'),
        ),
    ]
