# Generated by Django 6.0.2 on 2026-03-14 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_goal_end_date_goal_goal_item_goal_goal_item_unit_and_more'),
        ('tracker', '0009_alter_unit_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HigherGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('higher_goal', models.CharField(max_length=1024)),
            ],
        ),
        migrations.AlterField(
            model_name='goal',
            name='goal_item_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.unit'),
        ),
        migrations.AddField(
            model_name='goal',
            name='higher_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goals.highergoal'),
        ),
    ]
