# Generated by Django 6.0.2 on 2026-03-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_highergoal_alter_goal_goal_item_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='progression_number',
            field=models.IntegerField(default=1),
        ),
    ]
