# Generated by Django 6.0.2 on 2026-03-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_goal_progression_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='parent',
        ),
        migrations.AddField(
            model_name='goal',
            name='related_goals',
            field=models.ManyToManyField(related_name='related_goals', to='goals.goal'),
        ),
    ]
