# Generated by Django 6.0.2 on 2026-03-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0005_remove_goal_parent_goal_related_goals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='related_goals',
            field=models.ManyToManyField(to='goals.goal'),
        ),
    ]
