# Generated by Django 6.0.2 on 2026-03-14 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0006_alter_goal_related_goals'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='goals.goal'),
        ),
    ]
