# Generated by Django 6.0.2 on 2026-03-14 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0007_goal_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='goals.goal'),
        ),
    ]
