# Generated by Django 6.0.2 on 2026-03-14 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0008_alter_goal_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='parent',
        ),
    ]
