# Generated by Django 6.0.2 on 2026-03-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0009_remove_goal_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='target_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='target_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='related_goals',
            field=models.ManyToManyField(blank=True, null=True, to='goals.goal'),
        ),
    ]
