# Generated by Django 6.0.2 on 2026-03-14 18:22

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0010_goal_target_date_goal_target_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='start_date',
            field=models.DateField(db_default=django.db.models.functions.datetime.Now()),
        ),
    ]
