# Generated by Django 6.0.2 on 2026-03-15 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0011_alter_goal_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='target_type',
            field=models.CharField(choices=[('min', 'minimum'), ('max', 'maximum')], default='min'),
        ),
    ]
