# Generated by Django 6.0.2 on 2026-03-15 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0012_goal_target_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='target_type',
            field=models.CharField(choices=[('min', 'minimum'), ('max', 'maximum'), ('exact', 'exact')], default='min'),
        ),
    ]
