# Generated by Django 6.0.2 on 2026-03-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0014_alter_goal_related_goals'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalTrial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='goal',
            name='trial_number',
            field=models.IntegerField(default=1),
        ),
    ]
