# Generated by Django 6.0.2 on 2026-03-21 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0015_goaltrial_goal_trial_number'),
        ('tracker', '0014_record_end_level_record_start_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Vision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_num', models.IntegerField(blank=True, null=True, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('current_avg', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('s', 'succeeded'), ('f', 'failed'), ('a', 'active'), ('u', 'unstarted')], default='u')),
                ('habit_tracked', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.item')),
                ('progression', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goals.progression')),
            ],
        ),
    ]
