# Generated by Django 6.0.2 on 2026-03-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0016_progression_vision_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='status',
            field=models.CharField(choices=[('s', 'succeeded'), ('f', 'failed'), ('a', 'active'), ('u', 'unstarted'), ('m', 'maintenance')], default='u'),
        ),
    ]
