# Generated by Django 6.0.2 on 2026-03-23 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0017_alter_level_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='goal',
            new_name='name',
        ),
    ]
