# Generated by Django 6.0.2 on 2026-03-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0018_rename_goal_goal_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='goal',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
