# Generated by Django 6.0.2 on 2026-03-22 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movementlog',
            name='movt_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
