# Generated by Django 6.0.2 on 2026-03-21 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=1024)),
                ('product_type', models.CharField(choices=[('l', 'Liquid'), ('s', 'Solid'), ('se', 'Service')])),
                ('product_units', models.CharField(blank=True, choices=[('ml', 'mililitre'), ('g', 'gram'), ('kg', 'kilogram'), ('m', 'months')], max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('record_units', models.CharField(choices=[('ml', 'mililitre'), ('g', 'gram'), ('kg', 'kilogram'), ('m', 'months')])),
                ('qty_bought', models.FloatField(blank=True, null=True)),
                ('total_price', models.FloatField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_records.product')),
            ],
        ),
    ]
