# Generated by Django 6.0.2 on 2026-03-21 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='product_units',
            field=models.CharField(blank=True, choices=[('ml', 'millilitre'), ('L', 'Litre'), ('g', 'gram'), ('kg', 'kilogram'), ('m', 'months'), ('loaf', 'Loaf'), ('u', 'Unit')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='record_units',
            field=models.CharField(choices=[('ml', 'millilitre'), ('L', 'Litre'), ('g', 'gram'), ('kg', 'kilogram'), ('m', 'months'), ('loaf', 'Loaf'), ('u', 'Unit')]),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial_records.brand'),
        ),
    ]
