# Generated by Django 6.0.2 on 2026-03-21 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_records', '0005_flavor'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='flavor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial_records.flavor'),
        ),
    ]
