# Generated by Django 6.0.2 on 2026-03-21 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_records', '0006_record_flavor'),
    ]

    operations = [
        migrations.AddField(
            model_name='flavor',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financial_records.brand'),
        ),
    ]
