# Generated by Django 6.0.2 on 2026-03-22 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_records', '0007_flavor_brand'),
        ('movements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='movement_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movements.movementlog'),
        ),
    ]
