# Generated by Django 6.0.2 on 2026-03-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_records', '0008_record_movement_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='packaging',
            field=models.CharField(blank=True, choices=[('sachet', 'Sachet'), ('bottle', 'Bottle'), ('packet', 'packet'), ('can', 'Can')], default='sachet', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('liquid', 'Liquid'), ('solid', 'Solid'), ('service', 'Service'), ('powder', 'Powder')]),
        ),
    ]
