# Generated by Django 6.0.2 on 2026-03-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_records', '0009_branch_record_packaging_alter_product_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='packaging_material',
            field=models.CharField(blank=True, choices=[('plastic', 'Plastic'), ('polyethene', 'Polyethene'), ('aluminium', 'Aluminium')], default='plastic', null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='packaging',
            field=models.CharField(blank=True, choices=[('sachet', 'Sachet'), ('bottle', 'Bottle'), ('packet', 'packet'), ('can', 'Can'), ('tin', 'Tin')], default='sachet', null=True),
        ),
    ]
