# Generated by Django 6.0.2 on 2026-03-25 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_records', '0010_record_packaging_material_alter_record_packaging'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(max_length=1024)),
            ],
        ),
    ]
