# Generated by Django 6.0.2 on 2026-03-25 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_records', '0011_foodproductvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='food_product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial_records.foodproductvariant'),
        ),
    ]
