# Generated by Django 6.0.2 on 2026-03-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_records', '0012_record_food_product_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='packaging',
            field=models.CharField(blank=True, choices=[('sachet', 'Sachet'), ('bottle', 'Bottle'), ('packet', 'packet'), ('can', 'Can'), ('tin', 'Tin'), ('polythene', 'Polyethene')], default='sachet', null=True),
        ),
    ]
