# Generated by Django 6.0.2 on 2026-04-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_records', '0013_alter_record_packaging'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='record_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_units',
            field=models.CharField(blank=True, choices=[('ml', 'millilitre'), ('L', 'Litre'), ('g', 'gram'), ('kg', 'kilogram'), ('m', 'months'), ('loaf', 'Loaf'), ('u', 'Unit'), ('t', 'Trip')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='packaging',
            field=models.CharField(blank=True, choices=[('sachet', 'Sachet'), ('bottle', 'Bottle'), ('packet', 'packet'), ('can', 'Can'), ('tin', 'Tin'), ('polythene', 'Polyethene'), ('paperbag', 'Paperbag'), ('box', 'Box')], default='sachet', null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='packaging_material',
            field=models.CharField(blank=True, choices=[('plastic', 'Plastic'), ('polyethene', 'Polyethene'), ('aluminium', 'Aluminium'), ('paper', 'Paper')], default='plastic', null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='record_units',
            field=models.CharField(choices=[('ml', 'millilitre'), ('L', 'Litre'), ('g', 'gram'), ('kg', 'kilogram'), ('m', 'months'), ('loaf', 'Loaf'), ('u', 'Unit'), ('t', 'Trip')]),
        ),
    ]
