# Generated by Django 6.0.2 on 2026-04-09 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_records', '0014_record_record_notes_alter_product_product_units_and_more'),
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.place'),
        ),
    ]
