# Generated by Django 6.0.2 on 2026-04-09 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_records', '0015_record_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='place',
        ),
    ]
