# Generated by Django 6.0.2 on 2026-04-09 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_records', '0016_remove_record_place'),
        ('places', '0002_address_area_city_country_delete_place_address_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='places.address'),
        ),
        migrations.AddField(
            model_name='branch',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='name',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='branch',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches', to='financial_records.vendor'),
        ),
        migrations.AddField(
            model_name='record',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial_records.branch'),
        ),
    ]
