# Generated by Django 6.0.2 on 2026-04-09 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_records', '0017_branch_address_branch_is_active_branch_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name_plural': 'branches'},
        ),
    ]
