# Generated by Django 6.0.2 on 2026-04-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_records', '0018_alter_branch_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('liquid', 'Liquid'), ('solid', 'Solid'), ('service', 'Service'), ('powder', 'Powder'), ('physica', 'Physical')]),
        ),
    ]
