# Generated by Django 6.0.2 on 2026-04-17 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_records', '0019_alter_product_product_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-product_name']},
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['-transaction_date']},
        ),
    ]
