# Generated by Django 6.0.2 on 2026-03-14 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promise', models.CharField(max_length=1024)),
                ('related_goals', models.ManyToManyField(blank=True, null=True, to='goals.goal')),
            ],
        ),
    ]
