# Generated by Django 6.0.2 on 2026-03-15 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0014_alter_goal_related_goals'),
        ('promises', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promise',
            name='related_goals',
            field=models.ManyToManyField(blank=True, to='goals.goal'),
        ),
    ]
