# Generated by Django 6.0.2 on 2026-03-16 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='socialmediahandle',
            name='entity',
        ),
    ]
