# Generated by Django 6.0.2 on 2026-03-16 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_remove_email_entity_remove_phonenumber_entity_and_more'),
        ('entity', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='entity.entity'),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='entity.entity'),
        ),
        migrations.AddField(
            model_name='socialmediahandle',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_media_handles', to='entity.entity'),
        ),
    ]
