# Generated by Django 6.0.2 on 2026-03-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_email_entity_phonenumber_entity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediahandle',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('telegram', 'Telegram'), ('youtube', 'YouTube')], default='facebook'),
        ),
    ]
