# Generated by Django 6.0.2 on 2026-04-11 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_socialmediahandle_platform'),
        ('entity', '0004_entitytype_remove_entity_name_entity_entity_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(max_length=200)),
                ('link_url', models.CharField(max_length=200)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generic_links', to='entity.entity')),
            ],
        ),
    ]
