# Generated by Django 6.0.2 on 2026-04-09 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_address_area_city_country_delete_place_address_area_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'addresses'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'countries'},
        ),
    ]
