# Generated by Django 6.0.2 on 2026-03-16 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_remove_email_entity_remove_phonenumber_entity_and_more'),
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entity',
        ),
    ]
