# Generated by Django 6.0.2 on 2026-03-16 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0003_initial'),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='from_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing', to='entity.entity'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='to_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming', to='entity.entity'),
        ),
        migrations.DeleteModel(
            name='Entity',
        ),
    ]
