# Generated by Django 6.0.2 on 2026-03-16 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_alter_relation_from_entity_alter_relation_to_entity_and_more'),
    ]

    operations = [
    ]
