# Generated by Django 6.0.2 on 2026-03-16 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_auto_20260316_1750'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cat',
        ),
        migrations.DeleteModel(
            name='Institution',
        ),
    ]
