# Generated by Django 6.0.2 on 2026-03-16 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_delete_cat_delete_institution'),
    ]

    operations = [
    ]
