# Generated by Django 6.0.2 on 2026-03-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_date', models.DateField()),
                ('journal_time', models.TimeField()),
                ('journal_content', models.TextField()),
            ],
        ),
    ]
