# Generated by Django 6.0.2 on 2026-04-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='last_modificication_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='journal_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='journal_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
