# Generated by Django 6.0.2 on 2026-04-10 18:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entity', '0004_entitytype_remove_entity_name_entity_entity_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('requires_depreciation', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Asset Categories',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('current_value', models.DecimalField(decimal_places=2, help_text='Current estimated value (updated via depreciation)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('purchase_date', models.DateField()),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('disposal_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('disposed', 'Disposed'), ('lost', 'Lost')], default='active', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assets', to='entity.entity')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.assetcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetValuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField(help_text='Why value was adjusted (market change, damage, restoration, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='accounts.asset')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_valuations', to='entity.entity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DepreciationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('straight_line', 'Straight Line'), ('declining_balance', 'Declining Balance'), ('no_depreciation', 'No Depreciation')], max_length=20)),
                ('annual_rate', models.DecimalField(decimal_places=4, help_text='Annual depreciation rate (e.g., 0.20 for 20%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('useful_life_years', models.IntegerField(default=5, help_text='Expected useful life in years', validators=[django.core.validators.MinValueValidator(1)])),
                ('salvage_value', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Estimated value at end of useful life', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_policies', to='accounts.asset')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.entity')),
            ],
            options={
                'verbose_name_plural': 'Owners',
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='accounts.owner'),
        ),
        migrations.CreateModel(
            name='PhysicalAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('serial_number', models.CharField(blank=True, max_length=255, unique=True)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('non_functional', 'Non-Functional')], default='good', max_length=20)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Device-specific specs: storage_gb, ram_gb, screen_size, cpu, etc.')),
                ('location', models.CharField(blank=True, max_length=255)),
                ('is_in_use', models.BooleanField(default=True)),
                ('warranty_provider', models.CharField(blank=True, max_length=255)),
                ('warranty_type', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='physical_asset', to='accounts.asset')),
            ],
            options={
                'verbose_name_plural': 'Physical Assets',
            },
        ),
        migrations.CreateModel(
            name='AssetLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('depreciation_calculated', 'Depreciation Calculated'), ('status_changed', 'Status Changed'), ('value_adjusted', 'Value Adjusted'), ('investment_added', 'Investment Added'), ('investment_completed', 'Investment Completed'), ('deleted', 'Deleted')], max_length=50)),
                ('description', models.TextField()),
                ('changes', models.JSONField(blank=True, default=dict, help_text="Stores before/after values: {'field_name': {'old': value, 'new': value}}")),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='accounts.asset')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_logs', to='entity.entity')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['asset', 'created_at'], name='accounts_as_asset_i_e1fda0_idx'), models.Index(fields=['action', 'created_at'], name='accounts_as_action_bc7471_idx')],
            },
        ),
        migrations.CreateModel(
            name='DepreciationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('depreciated_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('depreciation_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('calculated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('calculation_period', models.DateField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_records', to='accounts.asset')),
                ('depreciation_policy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.depreciationpolicy')),
            ],
            options={
                'ordering': ['-calculated_at'],
                'indexes': [models.Index(fields=['asset', 'calculated_at'], name='accounts_de_asset_i_e76601_idx')],
            },
        ),
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('checking', 'Checking'), ('savings', 'Savings'), ('investment', 'Investment'), ('money_market', 'Money Market'), ('cd', 'Certificate of Deposit'), ('crypto_wallet', 'Crypto Wallet')], max_length=20)),
                ('account_number', models.CharField(blank=True, max_length=100)),
                ('bank_name', models.CharField(max_length=255)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('current_balance', models.DecimalField(decimal_places=2, help_text='Most recent balance', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=4, default=Decimal('0'), help_text='Annual interest rate (e.g., 0.0450 for 4.50%)', max_digits=6)),
                ('opened_date', models.DateField()),
                ('closed_date', models.DateField(blank=True, null=True)),
                ('last_statement_date', models.DateField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_account', to='accounts.asset')),
            ],
            options={
                'unique_together': {('bank_name', 'account_number')},
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('repair', 'Repair'), ('maintenance', 'Maintenance'), ('upgrade', 'Upgrade'), ('replacement_part', 'Replacement Part'), ('insurance', 'Insurance'), ('inspection', 'Inspection'), ('restoration', 'Restoration'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('planned_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('service_provider', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('receipt_url', models.URLField(blank=True, help_text='Link to digital receipt or documentation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='accounts.asset')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_investments', to='entity.entity')),
            ],
            options={
                'ordering': ['-planned_date'],
                'indexes': [models.Index(fields=['asset', 'status'], name='accounts_in_asset_i_a55324_idx'), models.Index(fields=['asset', 'type'], name='accounts_in_asset_i_35f194_idx'), models.Index(fields=['completed_date'], name='accounts_in_complet_9a61cd_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['owner', 'status'], name='accounts_as_owner_i_e890d2_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['category', 'status'], name='accounts_as_categor_b817ef_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['owner', 'category'], name='accounts_as_owner_i_80fb2a_idx'),
        ),
    ]
