# Generated by Django 6.0.2 on 2026-04-10 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('contacts', '0004_alter_socialmediahandle_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.email'),
        ),
    ]
