# Generated by Django 6.0.2 on 2026-04-10 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_owner_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='email',
        ),
    ]
