# Generated by Django 6.0.2 on 2026-04-10 18:55

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_owner_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='current_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current estimated value (updated via depreciation)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='asset',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='name',
            field=models.CharField(choices=[('bank_account', 'Bank Account'), ('savings_account', 'Savings Account'), ('cash_account', 'Cash Account'), ('investment_account', 'Investment Account'), ('smartphone', 'Smartphone'), ('laptop', 'Laptop'), ('desktop', 'Desktop Computer'), ('tablet', 'Tablet'), ('monitor', 'Monitor'), ('camera', 'Camera'), ('vehicle', 'Vehicle'), ('furniture', 'Furniture'), ('jewelry', 'Jewelry'), ('other', 'Other')], max_length=50, unique=True),
        ),
    ]
