# Generated by Django 6.0.2 on 2026-04-11 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_asset_current_value_alter_asset_purchase_date_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('entity', '0004_entitytype_remove_entity_name_entity_entity_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BankAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac_name', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=10)),
                ('opening_date', models.DateTimeField()),
                ('closing_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CashAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('fx_rate', models.DecimalField(decimal_places=2, default=1, max_digits=1000)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='assetlog',
            name='accounts_as_asset_i_e1fda0_idx',
        ),
        migrations.RemoveIndex(
            model_name='assetlog',
            name='accounts_as_action_bc7471_idx',
        ),
        migrations.RemoveField(
            model_name='assetvaluation',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='assetvaluation',
            name='performed_by',
        ),
        migrations.RemoveField(
            model_name='depreciationpolicy',
            name='asset',
        ),
        migrations.RemoveIndex(
            model_name='depreciationrecord',
            name='accounts_de_asset_i_e76601_idx',
        ),
        migrations.AlterUniqueTogether(
            name='financialaccount',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='financialaccount',
            name='asset',
        ),
        migrations.RemoveIndex(
            model_name='investment',
            name='accounts_in_asset_i_a55324_idx',
        ),
        migrations.RemoveIndex(
            model_name='investment',
            name='accounts_in_asset_i_35f194_idx',
        ),
        migrations.RemoveIndex(
            model_name='investment',
            name='accounts_in_complet_9a61cd_idx',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='user',
        ),
        migrations.AlterField(
            model_name='asset',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entity.entity'),
        ),
        migrations.RemoveField(
            model_name='physicalasset',
            name='asset',
        ),
        migrations.AlterModelOptions(
            name='asset',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='asset',
            name='accounts_as_owner_i_e890d2_idx',
        ),
        migrations.RemoveIndex(
            model_name='asset',
            name='accounts_as_categor_b817ef_idx',
        ),
        migrations.RemoveIndex(
            model_name='asset',
            name='accounts_as_owner_i_80fb2a_idx',
        ),
        migrations.AddField(
            model_name='asset',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='current_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=1000),
        ),
        migrations.AlterField(
            model_name='asset',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.assettype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankasset',
            name='asset_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.asset'),
        ),
        migrations.AddField(
            model_name='bankasset',
            name='managing_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entity.entity'),
        ),
        migrations.AddField(
            model_name='cashasset',
            name='asset_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.asset'),
        ),
        migrations.AddField(
            model_name='cashasset',
            name='managing_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entity.entity'),
        ),
        migrations.AddField(
            model_name='cryptoasset',
            name='asset_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.asset'),
        ),
        migrations.AddField(
            model_name='cryptoasset',
            name='managing_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entity.entity'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='from_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_account', to='accounts.asset'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_account', to='accounts.asset'),
        ),
        migrations.RemoveField(
            model_name='assetlog',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='assetlog',
            name='performed_by',
        ),
        migrations.DeleteModel(
            name='AssetValuation',
        ),
        migrations.RemoveField(
            model_name='depreciationrecord',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='depreciationrecord',
            name='depreciation_policy',
        ),
        migrations.DeleteModel(
            name='FinancialAccount',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
        migrations.DeleteModel(
            name='PhysicalAsset',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='category',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='description',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='disposal_date',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='name',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='status',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='warranty_expiry',
        ),
        migrations.DeleteModel(
            name='AssetLog',
        ),
        migrations.DeleteModel(
            name='DepreciationPolicy',
        ),
        migrations.DeleteModel(
            name='DepreciationRecord',
        ),
        migrations.DeleteModel(
            name='Investment',
        ),
        migrations.DeleteModel(
            name='AssetCategory',
        ),
    ]
