# Generated by Django 6.0.2 on 2026-04-11 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_assettype_bankasset_cashasset_cryptoasset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashasset',
            name='asset_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.assettype'),
        ),
    ]
