# Generated by Django 6.0.2 on 2026-04-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_cashasset_asset_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashasset',
            name='asset_nickname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
