# Generated by Django 6.0.2 on 2026-04-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_cashasset_asset_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankasset',
            name='current_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=1000, null=True),
        ),
        migrations.AddField(
            model_name='cashasset',
            name='current_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=1000, null=True),
        ),
        migrations.AddField(
            model_name='cryptoasset',
            name='current_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=1000, null=True),
        ),
    ]
