# Generated by Django 6.0.2 on 2026-04-11 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_bankasset_current_value_cashasset_current_value_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankasset',
            old_name='ac_name',
            new_name='asset_nickname',
        ),
    ]
