# Generated by Django 6.0.2 on 2026-04-11 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_ac_name_bankasset_asset_nickname'),
        ('forexchange', '0002_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankasset',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forexchange.currency'),
        ),
        migrations.AlterField(
            model_name='cashasset',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forexchange.currency'),
        ),
        migrations.AlterField(
            model_name='cryptoasset',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forexchange.currency'),
        ),
    ]
