# Generated by Django 6.0.2 on 2026-04-11 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_bankasset_currency_alter_cashasset_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankasset',
            name='asset_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.assettype'),
        ),
        migrations.AlterField(
            model_name='cryptoasset',
            name='asset_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.assettype'),
        ),
    ]
