# Generated by Django 6.0.2 on 2026-04-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_bankasset_asset_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptoasset',
            name='asset_nickname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
