# Generated by Django 6.0.2 on 2026-04-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MealLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField(auto_now_add=True)),
                ('log_time', models.TimeField(blank=True, null=True)),
                ('meal_type', models.CharField(choices=[('break', 'breakfast'), ('lunch', 'lunch'), ('supper', 'supper'), ('snack', 'snack')], default='snack')),
                ('what_was_eaten', models.TextField()),
                ('extra_notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
