# Generated by Django 6.0.2 on 2026-02-28 12:54

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('description', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('description', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('item_type', models.CharField(choices=[('qty', 'How much of something happens'), ('inst', 'When something happens')], max_length=1024)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tracker.category')),
                ('tag', models.ManyToManyField(to='tracker.tag')),
                ('related_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recored', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('quantity', models.FloatField()),
                ('action_time', models.DateTimeField()),
                ('record_notes', models.CharField(max_length=1024)),
                ('related_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.item')),
            ],
        ),
    ]
