# Generated by Django 6.0.2 on 2026-02-28 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='record',
            old_name='date_recored',
            new_name='date_recorded',
        ),
    ]
