# Generated by Django 6.0.2 on 2026-02-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
