# Generated by Django 6.0.2 on 2026-02-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_record_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='action_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
