# Generated by Django 6.0.2 on 2026-02-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_record_action_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='record_notes',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
