# Generated by Django 6.0.2 on 2026-02-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_record_record_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='related_unit',
            new_name='unit',
        ),
        migrations.AddField(
            model_name='record',
            name='happened',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('qty', 'How much of something happens'), ('inst', 'When something happens'), ('bool', 'If something happens')], max_length=1024),
        ),
    ]
