# Generated by Django 6.0.2 on 2026-03-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_rename_related_unit_item_unit_record_happened_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='tracker.tag'),
        ),
    ]
