# Generated by Django 6.0.2 on 2026-03-14 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_alter_item_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='record_string',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
