# Generated by Django 6.0.2 on 2026-03-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_alter_unit_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='action_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='action_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
