# Generated by Django 6.0.2 on 2026-03-15 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_record_action_date_alter_record_action_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='action_time',
            new_name='action_end_time',
        ),
        migrations.AddField(
            model_name='record',
            name='action_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
