# Generated by Django 6.0.2 on 2026-03-15 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_rename_action_time_record_action_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tag',
            field=models.ManyToManyField(blank=True, to='tracker.tag'),
        ),
    ]
