# Generated by Django 6.0.2 on 2026-03-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_alter_item_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['-action_date', '-date_recorded']},
        ),
        migrations.AddField(
            model_name='item',
            name='hidden',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
