# Generated by Django 6.0.2 on 2026-03-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_alter_record_options_item_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='end_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='start_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('qty', 'How much of something happens'), ('inst', 'When something happens'), ('bool', 'If something happens'), ('prog', 'Going towards some goal')], max_length=1024),
        ),
    ]
