# Generated by Django 6.0.2 on 2026-04-17 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_record_end_level_record_start_level_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-name']},
        ),
    ]
